### ISSUE TITLE
Make Runner Flavour (Pod Resources) configurable

### ISSUE THREAD

**Issue by rafalgalaw** [mercedes-benz/garm-provider-k8s#23]
### What is the feature you would like to have?

Right now the runner flavour is a hard coded mapping to container requests and limits. It would be nice from a user perspective to provide a custom mapping of "runner flavours" to resource requests and limits in the runner container either in the provider config or pools extraSpec field like:

```yaml
flavour:
  micro:
    requests:
      cpu: 100m
      memory: 100Mi
    limits:
      memory: 200Mi
  medium:
    requests:
      cpu: 200m
      memory: 200Mi
    limits:
      memory: 300Mi
```
So one can reference `micro` or `medium` in a pool and the provider will spin pods with their respective resources
