### ISSUE TITLE
Custom labels through extra specs or podTemplate

### ISSUE THREAD

**Issue by Hdom** [mercedes-benz/garm-provider-k8s#28]
### What is the feature you would like to have?

I would like to be able to add custom labels through the extra specs or podTemplate.

I was hoping this was already possible and I tried enhancing the podTemplate in the provider config as follows:
```
podTemplate:
  metadata:
    labels:
      custom-label: custom-value
```
and it did not reflect successfully on the instance spec once deployed. 

This seems to be because the merge functionality specifically merged the Spec object inside of podTemplate.

### Anything else you would like to add?

We use labels for network filtering and this would be useful to be configurable.
